version: '3.5'

services:
  db:
    image: postgres:13.13
    env_file:
      - .env
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - konzisite_db_folder:/var/lib/postgresql/data
    networks:
      - konzisite-network
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && npm run start:prod"
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env
    volumes:
      - konzisite_static_folder:/usr/src/app/static
    networks:
      - konzisite-network
    restart: ${DOCKER_RESTART_POLICY}
    cap_add:
      - SYS_ADMIN
networks:
  konzisite-network:
volumes:
  konzisite_db_folder:
    external: true
  konzisite_static_folder:
    external: true
