version: '3.5'

services:
  db:
    image: postgres:13.5
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: konzisite
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - konzisite-network
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && npm run start:prod"
    ports:
      - '3006:3000' # The exposed port should be changed accordingly
    env_file:
      - .env
    networks:
      - konzisite-network
    restart: always
networks:
  konzisite-network:
