@startuml konzisite
'https://plantuml.com/class-diagram

[Consultation] -d- "1..*" [Presentation] : "presenters"
[Presentation] - "1" [User]
[Presentation] "1" - "0..*" [Rating]
[Consultation] -d- "1" [User] : "owner"
[Consultation] - "0..*" [Group] : "targetGroups"
[Consultation] -u- "0..*" [Participation] : "participants"
[Consultation] -u- "1"    [Subject] : "subject"

'Hidden connection for arranging the diagram
[User] -[hidden]- [Presentation]
[Group] -[hidden]- [User]
[Participation] -[hidden]- [Group]
[Subject] -[hidden]- [Participation]

[Participation] "1" -"1" [User]
[Participation] "1" -"0..*" [Rating]
[Group] "0..*"-"0..*" [User] : "membership"
[Subject] "0..*"-"0..*" [User] : "subscriptions"

[ConsultationRequest] "0..1" -"0..*" [Consultation] : "request"

[Subject] "1"-u- [ConsultationRequest] : "subject"
[User] "1"- [ConsultationRequest] : "initializer"
[User] "0..*"-d- [ConsultationRequest] : "supporter"

'Hidden connection for arranging the diagram
[User] -[hidden]- [Subject]
[User] -[hidden]- [User]


sprite $Logo [32x14/16]{
FFF00000000000FFF0FFFFFFFFFF0000
FFF00000000000FFF0FFFFFFFFFFFF00
FFF00000000000FFF0000000000FFFFF
0FFF0000000000FFF000000000000FFF
0FFFF000000000FFF000000000000FFF
000FFFF0000000FFF00000000000FFFF
0000FFFFFFFFF0FFF00FFFFFFFFFFFF0
00000FFFFFFFFFFFF0FFFFFFFFFF0000
000FFFFFF00000FFF000000FFFFFF000
00FFFF00000000FFF000000000FFFF00
0FFF0000000000FFF00000000000FFF0
FFF00000000000FFF000000000000FFF
FFF00000000000FFF000000000000FFF
FFF00000000000FFF0000000000000FF
}

rectangle "Kir-Dev" as logo<<$Logo>>

[Consultation] --[hidden]- logo


@enduml
